### PR TITLE
Add LICENSE.txt

### PR DESCRIPTION
**Pull request by rchavik**
@vitorpc @phpedinei

Since this is originally forked from your repo, can I get an ack for me to add a LICENSE.txt with the MIT license

Thanks

### CODE REVIEW

**Comment by vitorpacheco** [comment]
It's ok for me, but wait for the answer of @phpedinei, the job is his.

**Comment by rchavik** [comment]
@phpedinei Can I get an ack please?

Thanks

**Comment by phpedinei** [comment]
ok
thanks

**Comment by rchavik** [comment]
Thank you

**Pull request merged**
